### PR TITLE
Use org.glassfish.web.avax.servlet.jsp (continued)

### PR DESCRIPTION
**Pull request by mickaelistria**
Follow up on https://github.com/eclipse-platform/eclipse.platform.common/pull/106
Related to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/774

### CODE REVIEW

**Comment by mickaelistria** [comment]
@akurtakov Some tests are failing because of this change. I'm not familiar with the help application. Do you have some hint to troubleshot it?

**Comment by akurtakov** [comment]
Help system is broken today with:
```
<h2>HTTP ERROR 500 org.apache.jasper.JasperException: PWC6349: Cannot 
find a java compiler for compilation.  If running with JDK 5 or before, 
Ant or JDT compiler can be used, if the corresponding jars and bridge 
classes (org.apache.jasper.compiler.AntJavaCompiler or 
org.apache.jasper.compiler.JDTJavaCompiler) are included</h2>


URI: | /help/index.jsp
-- | --
500
org.apache.jasper.JasperException: PWC6349:  Cannot find a java compiler for compilation.  If running with JDK 5 or  before, Ant or JDT compiler can be used, if the corresponding jars and  bridge classes (org.apache.jasper.compiler.AntJavaCompiler or  org.apache.jasper.compiler.JDTJavaCompiler) are included
org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet-ecd9f6d
org.apache.jasper.JasperException: PWC6349:  Cannot find a java compiler for compilation.  If running with JDK 5 or  before, Ant or JDT compiler can be used, if the corresponding jars and  bridge classes (org.apache.jasper.compiler.AntJavaCompiler or  org.apache.jasper.compiler.JDTJavaCompiler) are included


<h3>Caused by:</h3><pre>org.apache.jasper.JasperException: PWC6349: Cannot find a java compiler for compilation.  If running with JDK 5 or before, Ant or JDT compiler can be used, if the corresponding jars and bridge classes (org.apache.jasper.compiler.AntJavaCompiler or org.apache.jasper.compiler.JDTJavaCompiler) are included
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:92)
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:378)
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:119)
	at org.apache.jasper.compiler.Compiler.initJavaCompiler(Compiler.java:783)</pre>
```

**Comment by akurtakov** [comment]
Looking at content of org.glassfish.web.javax.servlet.jsp_2.3.4.jar it doesn't contain JDTJavaCompiler.class. I have no idea about the dirty details in jasper.

**Comment by akurtakov** [comment]
There is smth in https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.equinox.jsp.jasper/src/org/eclipse/equinox/internal/jsp/jasper/Activator.java#L38 but I honestly don't understand it.

**Comment by iloveeclipse** [comment]
@mickaelistria : it would be nice to have **one issue** in some tracker that would be referenced by commits and by pull requests, so one can at least have an idea what's going on, what is done and what not. Right now there are only different closed pull requests in different repos with no hint what is still missing and a broken help subsystem with no opened issue for that.

**Comment by mickaelistria** [comment]
Won't merge; I'll restore to a working state and then close the topic.

**Pull request closed without merging**
