### PR TITLE
Fix master build

### PR DESCRIPTION
**Pull request by akurtakov**
As can be seen at
https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/master/109/console :
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.jdt.feature.group
3.19.0.v20230205-1800
[ERROR]   Missing requirement: org.eclipse.jdt 3.19.0.v20230204-1800
requires 'osgi.bundle; org.eclipse.ui.cheatsheets [3.2.0,4.0.0)' but it
could not be found
[ERROR]   Missing requirement: org.eclipse.jdt 3.19.0.v20230205-1800
requires 'osgi.bundle; org.eclipse.ui.cheatsheets [3.2.0,4.0.0)' but it
could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.jdt.feature.group
3.19.0.v20230204-1955 depends on: org.eclipse.equinox.p2.iu;
org.eclipse.jdt [3.19.0.v20230204-1800,3.19.0.v20230204-1800]
[ERROR]   Cannot satisfy dependency: org.eclipse.jdt.feature.group
3.19.0.v20230205-1800 depends on: org.eclipse.equinox.p2.iu;
org.eclipse.jdt [3.19.0.v20230205-1800,3.19.0.v20230205-1800]

```

### CODE REVIEW

**Comment by akurtakov** [comment]
@laeubi Is this caused by recent change in Tycho? Also do you have recommendation how to simplify this extra requirements list.

**Comment by akurtakov** [comment]
The target-platform-configuration is totally insane here and I have no idea how/why these bundles are there. Merging but this would better be revised to something manageable.

**Comment by laeubi** [comment]
> The target-platform-configuration is totally insane here

Yep, but your change looks reasonable.

If I remember correctly this because we collect from different actors items in one big artifact, probably it would getting better if we merge more repositories and thus remove inter-dpendency-cycles.

**Comment by laeubi** [comment]
>  Also do you have recommendation how to simplify this extra requirements list.

Tycho now support them to adding by the "additional.bundles" aka "Automatically managed dependencies" in PDE, that has the advantage that one can "manage" them from the UI instead of the pom as done here:
https://github.com/eclipse-platform/eclipse.platform/blob/489bf9a096c1d2ad2299c596707e8656568f16b0/update/org.eclipse.update.configurator.tests/build.properties

**Comment by laeubi** [comment]
I have investigated a bit more and it seems that there is an issue with the new resolver regarding test-dependencies are sometimes not found I can reproduce this also with equinox (what only use a simple target-platform configuration), I'll investigate this and seems I need to disable the resolver for now see:

**Comment by laeubi** [comment]
By the way I think initially this was intended to be handled by the following PDE feature:
- https://github.com/eclipse-pde/eclipse.pde/issues/451

but it seems it is currently broken, but I plan to revive this feature and add support for it (together with @HannesWell ) as this would solve some other cases as well.

**Pull request merged**
