### PR TITLE
Create updateRelease.yml

### PR DESCRIPTION
**Pull request by akurtakov**
Add workflow for automatic release updates

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov you can test the outcome of this with your private fork,

set the master to the commit you want to test (e.g. before the release update), then merge the yml file to your master branch and create a Milestone:

- Name it like the release (4.28)
- In the description write something that contains "Release" (or only this word)
- Then this will trigger the workflow in you repository and you can investigate the outcome.

**Comment by akurtakov** [comment]
I have created the milestone https://github.com/akurtakov/eclipse.platform.ua/milestone/1 but nothing happen, could I missing some setting for my fork?

**Comment by laeubi** [comment]
You must add the workflow to your forks master branch (you can reset it after all experiements are done) at laest here I can't see it:

https://github.com/akurtakov/eclipse.platform.ua/tree/master/.github/workflows

**Comment by akurtakov** [comment]
It's there now but still no PR.

**Comment by laeubi** [comment]
You need to be a bit patient the action is still running:
https://github.com/akurtakov/eclipse.platform.ua/actions

**Comment by akurtakov** [comment]
> You need to be a bit patient the action is still running: https://github.com/akurtakov/eclipse.platform.ua/actions

Wow, sorry !

**Comment by akurtakov** [comment]
OK, build failed on jsp compilation. I think I'll merge this one for next cycle to be automatic (hopefully!) and do the changes manually now.

**Comment by laeubi** [comment]
It might be because this relies on the ibuilds, I already opened tickets that we nee "next release ibuild" repos for such purpose....

**Comment by akurtakov** [comment]
Milestones has been created already so merge for next cycle and do the bumps manually.

**Pull request merged**
