### PR TITLE
Bug 202691 - [Cheatsheets] Edit->Copy and Ctrl+C do not copy selected text

### PR DESCRIPTION
**Pull request by N1k145**
Fixes Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=202691

The Copy action tried to always copy from the "current item" even when this was not the selected item.
The change checks for the first item with focus (which should be only one item) and executes the copy on that item.

### CODE REVIEW

**Comment by akurtakov** [comment]
Please sing Eclipse Contributor Agreement https://www.eclipse.org/legal/ecafaq.php so we are allowed to look into your patch.

**Comment by laeubi** [comment]
> so we are allowed to look into your patch.

I think it is always allowed to look at the patch ;-)

**Comment by N1k145** [comment]
@akurtakov @laeubi the ECA check worked now

**Comment by mickaelistria** [comment]
We try to avoid merge commits in the history to keep it readable. I'm not certain "Squash and Merge" fully resolves them. Would you mind rebasing your main commit on top of master and `git push --force` it to your topic branch so this PR gets updated?

**Comment by N1k145** [comment]
We use squash and merge for this usecase, then have only one commit in the history. But I don't know if git keeps track of these anyway

**Comment by mickaelistria** [comment]
Ok, let's try.

**Pull request merged**
