### PR TITLE
Adding a read me file for platform.ua

### PR DESCRIPTION
**Pull request by ShiyasTS**

### CODE REVIEW

**Comment by iloveeclipse** [comment]
1) Please provide a single commit without merge commits
2) Please remove any links to bugzilla (which is dead) from readme

**Comment by ShiyasTS** [comment]
> * Please provide a single commit without merge commits
> * Please remove any links to bugzilla (which is dead) from readme

Hi @iloveeclipse ,I have removed the links to bugzilla. Do I need to delete this PR and create a fresh PR with only one commit?

**Comment by iloveeclipse** [comment]
> Do I need to delete this PR and create a fresh PR with only one commit?

No. Please squash your commits to one and force push to github.

**Comment by wimjongman** [comment]
No need for additional force pushes. Thanks, @ShiyasTS!

**Pull request merged**
