### PR TITLE
Possible workaround for errors while checking non-file URLs

### PR DESCRIPTION
**Pull request by iloveeclipse**
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/136

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Note: I have to check if the old Lucene didn't found the entries below too:
```
Not a file?: http://127.0.0.1:33441/help/topic/org.eclipse.ui.intro.universal/qroot
Not a file?: http://127.0.0.1:33441/help/topic/org.eclipse.ui.intro.universal/overview
Not a file?: http://127.0.0.1:33441/help/topic/org.eclipse.ui.intro.universal/samples
Not a file?: http://127.0.0.1:33441/help/topic/org.eclipse.ui.intro.universal/whatsnew
Not a file?: http://127.0.0.1:33441/help/topic/org.eclipse.ui.intro.universal/standby
```

**Comment by akurtakov** [comment]
Is this one still needed?

**Comment by iloveeclipse** [comment]
> Is this one still needed?

On gerrit current test executes but never **properly test anything**, because it ignored "java.lang.IllegalStateException: Workbench has not been created yet" exceptions trying to create help system :-(

I've tried to fix the way tests run with tycho, see now different error which I don't understand:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (default) on project infocenter-app: An Ant BuildException has occured: /home/jenkins/agent/workspace/eclipse.platform.ua_PR-77/infocenter-web/infocenter-app/src/main/webapp/WEB-INF/plugins does not exist.
```

**Comment by laeubi** [comment]
> I've tried to fix the way tests run with tycho, see now different error which I don't understand:

probably because this an error from the **org.apache.maven.plugins:maven-antrun-plugin** and not Tycho ;-)

**Comment by iloveeclipse** [comment]
> > I've tried to fix the way tests run with tycho, see now different error which I don't understand:
> 
> probably because this an error from the **maven-antrun-plugin** and not Tycho ;-)

If you have an idea what is wrong here, please share it with the rest of the world.

**Comment by laeubi** [comment]
> > > I've tried to fix the way tests run with tycho, see now different error which I don't understand:
> > 
> > 
> > probably because this an error from the **maven-antrun-plugin** and not Tycho ;-)
> 
> If you have an idea what is wrong here, please share it with the rest of the world.

No idea, because this just calls some of the magic ant-scripts, so the only hint I can give is looking into the ant `build.xml` as Tycho is not doing anything here. From the error message it seems to miss a folder, if that itself the error or just a consequence of a previous failure (e.g. some files are not getting generated) I have no clue.

**Comment by iloveeclipse** [comment]
OK, now (for whatever reason after rebase) we have proper tests failing:

[org.eclipse.ua.tests.help.webapp.HelpServerInterrupt.testServerWithInterrupt](https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-77/3/testReport/junit/org.eclipse.ua.tests.help.webapp/HelpServerInterrupt/testServerWithInterrupt/)
[org.eclipse.ua.tests.help.webapp.HelpServerInterrupt.testServerWithoutInterrupt](https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-77/3/testReport/junit/org.eclipse.ua.tests.help.webapp/HelpServerInterrupt/testServerWithoutInterrupt/)
[org.eclipse.ua.tests.help.webapp.HelpServerBinding.testStandaloneBinding](https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-77/3/testReport/junit/org.eclipse.ua.tests.help.webapp/HelpServerBinding/testStandaloneBinding/)
[org.eclipse.ua.tests.help.webapp.HelpServerBinding.testInfocenterBinding](https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-77/3/testReport/junit/org.eclipse.ua.tests.help.webapp/HelpServerBinding/testInfocenterBinding/)
[org.eclipse.ua.tests.help.webapp.HelpServerBinding.testWorkbenchBinding](https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-77/3/testReport/junit/org.eclipse.ua.tests.help.webapp/HelpServerBinding/testWorkbenchBinding/)

**Comment by iloveeclipse** [comment]
OK, looks like the 5 failing tests are "always" failing, and they are also unrelated to the changes here (different test, and the changed test runs after failing one, so can't be the root cause) => merging.

**Comment by iloveeclipse** [comment]
I've opened https://github.com/eclipse-platform/eclipse.platform.ua/issues/82

**Pull request merged**
