### PR TITLE
Move webapp to Java 17 and update jetty jspc

### PR DESCRIPTION
**Pull request by akurtakov**
Move webapp to Java 17.

### CODE REVIEW

**Comment by akurtakov** [comment]
@laeubi Any idea what's wrong here https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-102/4/console ?

**Comment by laeubi** [comment]
The API tools fail with:

> File TipsStartupService.java at line 35: The import org.osgi.service.component cannot be resolved

This might be a bug in `tycho-dependency-tools-plugin` or nothing can be found at the target platform, if you can build this local, there should be a "dependeices.txt" or something in the target folder that list all items, I can try to take a look later if I see what happens here, but UI seems always a bit special, so maybe one needs to add an extra requirement here?

**Comment by akurtakov** [comment]
In local build there is /home/akurtakov/.m2/repository/org/osgi/org.osgi.service.component/1.5.1/org.osgi.service.component-1.5.1.jar in target/dependencies-list.txt file.

**Comment by mickaelistria** [comment]
I can reproduce the build issue from master, then `mvn clean verify -Pbuild-individual-bundles -Papi-check -pl org.eclipse.tips.ide`.

I'm trying to debug with `java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=1044 -Xmx2048M -jar /home/mistria/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.6.400.v20210924-0641/org.eclipse.equinox.launcher-1.6.400.v20210924-0641.jar -install /home/mistria/git/eclipse.platform.ua/apiAnalyzer-workspace -configuration /home/mistria/git/eclipse.platform.ua/apiAnalyzer-workspace/configuration -data /home/mistria/git/eclipse.platform.ua/apiAnalyzer-workspace/data -application org.eclipse.pde.api.tools.apiAnalyzer -project /home/mistria/git/eclipse.platform.ua/org.eclipse.tips.ide -baseline /home/mistria/git/eclipse.platform.ua/org.eclipse.tips.ide/target/org.eclipse.tips.ide-apiBaseline.target -dependencyList /home/mistria/git/eclipse.platform.ua/org.eclipse.tips.ide/target/dependencies-list.txt -failOnError` (the command generated by eclipse-run, with addition of debugging agent), when connecting to the application, I can see that the target platform seems to be properly resolved, includes the org.osgi.service.component bundle, that the org.eclipse.tips.ide project is imported but I don't see org.osgi.service.component in its resolved classpath (while both Tycho and PDE in my IDE seem to add it to the classpath).

`

**Comment by laeubi** [comment]
> while both Tycho and PDE in my IDE seem to add it to the classpath

Yes PDE do this automatically (also Tycho), but I don't know if that also applies to the API tools (e.g. do they use a full pde-core project setup?) Maybe something is required here due to the new release cycle so it can't fetch all requirements?!?

**Comment by mickaelistria** [comment]
Let's continue discussion about this API Tools issue in https://github.com/eclipse-platform/eclipse.platform.ua/issues/103

**Pull request merged**
